#
# Docker setups to test and develop this application.
#
# Build and run all tests via docker-compose up test
version: "3.0"
services:
  test:
    build: .
    volumes:
    - .:/code:z
    working_dir: /code
    entrypoint: /bin/sh
    command: -c 'pip install tox && tox ${TOXARGS}'

  idp:
    build:
      context: .
      dockerfile: Dockerfile.testenv
    hostname: spid.local
    volumes:
    - .:/code
    depends_on:
    - simple
    command: ["--dummy-config", "--insecure-add-sp", "https://simple/metadata"]

  simple:
    build: .
    hostname: simple
    working_dir: /code
    volumes:
    - .:/code
    environment:
      PYTHONPATH: "/code:"
    entrypoint: ["python", "-m", "service_provider"]
    command: ["--insecure-add-idp", "https://idp:8088/metadata"]

  aa:
    build: .
    hostname: simple
    working_dir: /code
    environment:
      PYTHONPATH: "/code:"
    volumes:
    - .:/code
    entrypoint: ["python", "-m", "attribute_authority"]
    command: ["--insecure-add-idp", "https://idp:8088/metadata"]
