x-commons:
  throttling_headers: &throttling_headers
    X-RateLimit-Limit:
      $ref: '#/components/headers/X-RateLimit-Limit'
    X-RateLimit-Remaining:
      $ref: '#/components/headers/X-RateLimit-Remaining'
    X-RateLimit-Reset:
      $ref: '#/components/headers/X-RateLimit-Reset'
  common_responses: &common_responses
    '400':
      $ref: '#/components/responses/400BadRequest'
    '429':
      $ref: '#/components/responses/429TooManyRequests'
    '503':
      $ref: '#/components/responses/503ServiceUnavailable'
    default:
      $ref: '#/components/responses/default'

openapi: 3.0.0
info:
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: https://twitter.com/ioggstream
  title: Ora esatta.
  version: 1.0.0
  x-api-id: 00000000-0000-0000-0000-000000000000
  x-audience:
  - public
  x-summary: Questa AA di prova ritorna una serie di attributi al chiamante.
  description: |
    #### Documentazione

    ##### Sottosezioni
    E' possibile utilizzare - con criterio - delle sottosezioni.

    #### Note

    Il servizio non richiede autenticazione, ma va' usato rispettando gli
    header di throttling esposti in conformita' alle Linee Guida del Modello di interoperabilita'.

    #### Informazioni tecniche ed esempi

    Esempio:

    ```
    http http://localhost:8443/datetime/v1/echo
    {
      'datetime': '2018-12-30T12:23:32Z'
    }
    ```
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
servers:
- description: Test server
  url: https://aa.example.com/aa/v1
- description: Development server
  url: https://localhost:8443/aa/v1
tags:
- description: Retrieve informations
  externalDocs:
    url: http://docs.my-api.com/pet-operations.htm
  name: public
paths:
  /:
    get:
      operationId: attribute_authority.index
      responses:
        200:
          content:
            application/json:
              schema:
                type: string
          description: A list to the possible paths.
      summary: metadata
  /attributes/driving_license/{taxCode}:
    post:
      description: |
        Ritorna la patente di guida associata ad un codice fiscale
      operationId: attribute_authority.get_attribute_simple
      parameters:
      - name: taxCode
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: A JWS containing a claim.
        required: true
        content:
          application/jose:
            schema:
              type: string
          application/json:
            schema:
              $ref: '#/components/schemas/AttributeRequest'

      responses:
        <<: *common_responses
        '200':
          content:
            application/jose: {}
          description: |
            Il server ha ritornato gli attributi richiesti.

      summary: Ritorna la patente di un soggetto.
      tags:
      - public
  /status:
    get:
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: attribute_authority.get_status
      responses:
        <<: *common_responses
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timestamps'
          description: |
            Il server ha ritornato lo status. In caso di problemi
            ritorna sempre un problem+json.
          headers:
            <<: *throttling_headers
      summary: Ritorna lo stato dell'applicazione.
      tags:
      - public
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        type: integer
  responses:
    400BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Bad Request
    404NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Not Found
    429TooManyRequests:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Too many requests
      headers:
        Retry-After:
          description: |-
            Retry contacting the endpoint *at least* after seconds.
            See https://tools.ietf.org/html/rfc7231#section-7.1.3
          schema:
            format: int32
            type: integer
        X-RateLimit-Limit:
          description: The number of allowed requests in the current period
          schema:
            format: int32
            type: integer
        X-RateLimit-Remaining:
          description: The number of remaining requests in the current period
          schema:
            format: int32
            type: integer
        X-RateLimit-Reset:
          description: The number of seconds left in the current period
          schema:
            format: int32
            type: integer
    503ServiceUnavailable:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Service Unavailable
      headers:
        Retry-After:
          description: |-
            Retry contacting the endpoint *at least* after seconds.
            See https://tools.ietf.org/html/rfc7231#section-7.1.3
          schema:
            format: int32
            type: integer
    default:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Unexpected error
  schemas:
    AttributeRequest:
      properties:
        request_token:
          description: A request token based jose+jws
          type: string
          example:
            v:
              description: versione della AA
            attributes:
              type: array
              item:
                type: string
    Attributes:
      type: array
      items:
        $ref: '#/components/schemas/Attribute'
    Attribute:
      type: object
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          example: https://tools.ietf.org/html/rfc7231#section-6.6.4
          format: uri
          type: string
      type: object
    Timestamps:
      description: Un Timestamp in RFC5424
      properties:
        timestamp:
          example: '2018-12-30T12:23:32Z'
          format: date-time
          type: string
      type: object
